import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className = "m-2 p-2"
      >
        <p className="text-3xl">Employee Managaer</p>
        {children}
      </body>
    </html>
  );
}
